version: "3.2"

services:
  ghasreview:
    image: ghcr.io/khulnasoft-labs/ghasreview:main
    container_name: ghasreview
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./config:/ghasreview/config
    security_opt:
      - no-new-privileges:true
